/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RetosRouteImport } from './routes/retos'
import { Route as RetoVerificacionRouteImport } from './routes/reto-verificacion'
import { Route as RetoDetalleRouteImport } from './routes/reto-detalle'
import { Route as RetoCoordinacionRouteImport } from './routes/reto-coordinacion'
import { Route as ReporteDetalleRouteImport } from './routes/reporte-detalle'
import { Route as ReportarRouteImport } from './routes/reportar'
import { Route as RegistraRouteImport } from './routes/registra'
import { Route as RecompensasRouteImport } from './routes/recompensas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NoticiaRouteImport } from './routes/noticia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HabitoRouteImport } from './routes/habito'
import { Route as GuiaSegregacionRouteImport } from './routes/guia-segregacion'
import { Route as GuiaPracticaRouteImport } from './routes/guia-practica'
import { Route as ExitoRouteImport } from './routes/exito'
import { Route as EcoscanRouteImport } from './routes/ecoscan'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as AprendeRouteImport } from './routes/aprende'
import { Route as IndexRouteImport } from './routes/index'

const RetosRoute = RetosRouteImport.update({
  id: '/retos',
  path: '/retos',
  getParentRoute: () => rootRouteImport,
} as any)
const RetoVerificacionRoute = RetoVerificacionRouteImport.update({
  id: '/reto-verificacion',
  path: '/reto-verificacion',
  getParentRoute: () => rootRouteImport,
} as any)
const RetoDetalleRoute = RetoDetalleRouteImport.update({
  id: '/reto-detalle',
  path: '/reto-detalle',
  getParentRoute: () => rootRouteImport,
} as any)
const RetoCoordinacionRoute = RetoCoordinacionRouteImport.update({
  id: '/reto-coordinacion',
  path: '/reto-coordinacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ReporteDetalleRoute = ReporteDetalleRouteImport.update({
  id: '/reporte-detalle',
  path: '/reporte-detalle',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportarRoute = ReportarRouteImport.update({
  id: '/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistraRoute = RegistraRouteImport.update({
  id: '/registra',
  path: '/registra',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensasRoute = RecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiaRoute = NoticiaRouteImport.update({
  id: '/noticia',
  path: '/noticia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitoRoute = HabitoRouteImport.update({
  id: '/habito',
  path: '/habito',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaSegregacionRoute = GuiaSegregacionRouteImport.update({
  id: '/guia-segregacion',
  path: '/guia-segregacion',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaPracticaRoute = GuiaPracticaRouteImport.update({
  id: '/guia-practica',
  path: '/guia-practica',
  getParentRoute: () => rootRouteImport,
} as any)
const ExitoRoute = ExitoRouteImport.update({
  id: '/exito',
  path: '/exito',
  getParentRoute: () => rootRouteImport,
} as any)
const EcoscanRoute = EcoscanRouteImport.update({
  id: '/ecoscan',
  path: '/ecoscan',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendeRoute = AprendeRouteImport.update({
  id: '/aprende',
  path: '/aprende',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprende': typeof AprendeRoute
  '/comunidad': typeof ComunidadRoute
  '/configuracion': typeof ConfiguracionRoute
  '/ecoscan': typeof EcoscanRoute
  '/exito': typeof ExitoRoute
  '/guia-practica': typeof GuiaPracticaRoute
  '/guia-segregacion': typeof GuiaSegregacionRoute
  '/habito': typeof HabitoRoute
  '/login': typeof LoginRoute
  '/noticia': typeof NoticiaRoute
  '/perfil': typeof PerfilRoute
  '/recompensas': typeof RecompensasRoute
  '/registra': typeof RegistraRoute
  '/reportar': typeof ReportarRoute
  '/reporte-detalle': typeof ReporteDetalleRoute
  '/reto-coordinacion': typeof RetoCoordinacionRoute
  '/reto-detalle': typeof RetoDetalleRoute
  '/reto-verificacion': typeof RetoVerificacionRoute
  '/retos': typeof RetosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprende': typeof AprendeRoute
  '/comunidad': typeof ComunidadRoute
  '/configuracion': typeof ConfiguracionRoute
  '/ecoscan': typeof EcoscanRoute
  '/exito': typeof ExitoRoute
  '/guia-practica': typeof GuiaPracticaRoute
  '/guia-segregacion': typeof GuiaSegregacionRoute
  '/habito': typeof HabitoRoute
  '/login': typeof LoginRoute
  '/noticia': typeof NoticiaRoute
  '/perfil': typeof PerfilRoute
  '/recompensas': typeof RecompensasRoute
  '/registra': typeof RegistraRoute
  '/reportar': typeof ReportarRoute
  '/reporte-detalle': typeof ReporteDetalleRoute
  '/reto-coordinacion': typeof RetoCoordinacionRoute
  '/reto-detalle': typeof RetoDetalleRoute
  '/reto-verificacion': typeof RetoVerificacionRoute
  '/retos': typeof RetosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprende': typeof AprendeRoute
  '/comunidad': typeof ComunidadRoute
  '/configuracion': typeof ConfiguracionRoute
  '/ecoscan': typeof EcoscanRoute
  '/exito': typeof ExitoRoute
  '/guia-practica': typeof GuiaPracticaRoute
  '/guia-segregacion': typeof GuiaSegregacionRoute
  '/habito': typeof HabitoRoute
  '/login': typeof LoginRoute
  '/noticia': typeof NoticiaRoute
  '/perfil': typeof PerfilRoute
  '/recompensas': typeof RecompensasRoute
  '/registra': typeof RegistraRoute
  '/reportar': typeof ReportarRoute
  '/reporte-detalle': typeof ReporteDetalleRoute
  '/reto-coordinacion': typeof RetoCoordinacionRoute
  '/reto-detalle': typeof RetoDetalleRoute
  '/reto-verificacion': typeof RetoVerificacionRoute
  '/retos': typeof RetosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprende'
    | '/comunidad'
    | '/configuracion'
    | '/ecoscan'
    | '/exito'
    | '/guia-practica'
    | '/guia-segregacion'
    | '/habito'
    | '/login'
    | '/noticia'
    | '/perfil'
    | '/recompensas'
    | '/registra'
    | '/reportar'
    | '/reporte-detalle'
    | '/reto-coordinacion'
    | '/reto-detalle'
    | '/reto-verificacion'
    | '/retos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprende'
    | '/comunidad'
    | '/configuracion'
    | '/ecoscan'
    | '/exito'
    | '/guia-practica'
    | '/guia-segregacion'
    | '/habito'
    | '/login'
    | '/noticia'
    | '/perfil'
    | '/recompensas'
    | '/registra'
    | '/reportar'
    | '/reporte-detalle'
    | '/reto-coordinacion'
    | '/reto-detalle'
    | '/reto-verificacion'
    | '/retos'
  id:
    | '__root__'
    | '/'
    | '/aprende'
    | '/comunidad'
    | '/configuracion'
    | '/ecoscan'
    | '/exito'
    | '/guia-practica'
    | '/guia-segregacion'
    | '/habito'
    | '/login'
    | '/noticia'
    | '/perfil'
    | '/recompensas'
    | '/registra'
    | '/reportar'
    | '/reporte-detalle'
    | '/reto-coordinacion'
    | '/reto-detalle'
    | '/reto-verificacion'
    | '/retos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprendeRoute: typeof AprendeRoute
  ComunidadRoute: typeof ComunidadRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  EcoscanRoute: typeof EcoscanRoute
  ExitoRoute: typeof ExitoRoute
  GuiaPracticaRoute: typeof GuiaPracticaRoute
  GuiaSegregacionRoute: typeof GuiaSegregacionRoute
  HabitoRoute: typeof HabitoRoute
  LoginRoute: typeof LoginRoute
  NoticiaRoute: typeof NoticiaRoute
  PerfilRoute: typeof PerfilRoute
  RecompensasRoute: typeof RecompensasRoute
  RegistraRoute: typeof RegistraRoute
  ReportarRoute: typeof ReportarRoute
  ReporteDetalleRoute: typeof ReporteDetalleRoute
  RetoCoordinacionRoute: typeof RetoCoordinacionRoute
  RetoDetalleRoute: typeof RetoDetalleRoute
  RetoVerificacionRoute: typeof RetoVerificacionRoute
  RetosRoute: typeof RetosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/retos': {
      id: '/retos'
      path: '/retos'
      fullPath: '/retos'
      preLoaderRoute: typeof RetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reto-verificacion': {
      id: '/reto-verificacion'
      path: '/reto-verificacion'
      fullPath: '/reto-verificacion'
      preLoaderRoute: typeof RetoVerificacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reto-detalle': {
      id: '/reto-detalle'
      path: '/reto-detalle'
      fullPath: '/reto-detalle'
      preLoaderRoute: typeof RetoDetalleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reto-coordinacion': {
      id: '/reto-coordinacion'
      path: '/reto-coordinacion'
      fullPath: '/reto-coordinacion'
      preLoaderRoute: typeof RetoCoordinacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporte-detalle': {
      id: '/reporte-detalle'
      path: '/reporte-detalle'
      fullPath: '/reporte-detalle'
      preLoaderRoute: typeof ReporteDetalleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportar': {
      id: '/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof ReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registra': {
      id: '/registra'
      path: '/registra'
      fullPath: '/registra'
      preLoaderRoute: typeof RegistraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompensas': {
      id: '/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof RecompensasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticia': {
      id: '/noticia'
      path: '/noticia'
      fullPath: '/noticia'
      preLoaderRoute: typeof NoticiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habito': {
      id: '/habito'
      path: '/habito'
      fullPath: '/habito'
      preLoaderRoute: typeof HabitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-segregacion': {
      id: '/guia-segregacion'
      path: '/guia-segregacion'
      fullPath: '/guia-segregacion'
      preLoaderRoute: typeof GuiaSegregacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-practica': {
      id: '/guia-practica'
      path: '/guia-practica'
      fullPath: '/guia-practica'
      preLoaderRoute: typeof GuiaPracticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exito': {
      id: '/exito'
      path: '/exito'
      fullPath: '/exito'
      preLoaderRoute: typeof ExitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecoscan': {
      id: '/ecoscan'
      path: '/ecoscan'
      fullPath: '/ecoscan'
      preLoaderRoute: typeof EcoscanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprende': {
      id: '/aprende'
      path: '/aprende'
      fullPath: '/aprende'
      preLoaderRoute: typeof AprendeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprendeRoute: AprendeRoute,
  ComunidadRoute: ComunidadRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  EcoscanRoute: EcoscanRoute,
  ExitoRoute: ExitoRoute,
  GuiaPracticaRoute: GuiaPracticaRoute,
  GuiaSegregacionRoute: GuiaSegregacionRoute,
  HabitoRoute: HabitoRoute,
  LoginRoute: LoginRoute,
  NoticiaRoute: NoticiaRoute,
  PerfilRoute: PerfilRoute,
  RecompensasRoute: RecompensasRoute,
  RegistraRoute: RegistraRoute,
  ReportarRoute: ReportarRoute,
  ReporteDetalleRoute: ReporteDetalleRoute,
  RetoCoordinacionRoute: RetoCoordinacionRoute,
  RetoDetalleRoute: RetoDetalleRoute,
  RetoVerificacionRoute: RetoVerificacionRoute,
  RetosRoute: RetosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
